package mcworldinspector.utils;

import java.awt.Component;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author matthias
 */
public class MultipleErrorsDialog extends JDialog {

    private final AbstractTableModel errorTableModel;

    private MultipleErrorsDialog(Component owner, String title, boolean modal, List<FileError> errors) {
        super(owner, title, modal);
        this.errorTableModel = new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return errors.size();
            }

            @Override
            public int getColumnCount() {
                return 3;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                final FileError error = errors.get(rowIndex);
                switch (columnIndex) {
                    case 0: return error.getFile().toString();
                    case 1:
                        if (error instanceof FileOffsetError)
                            return Long.toString(((FileOffsetError)error).getOffset());
                        else if(error instanceof FileErrorWithExtra)
                            return Objects.toString(((FileErrorWithExtra)error).getExtra());
                        else
                            return "";
                    case 2: return error.getError().toString();
                    default: throw new AssertionError();
                }
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return String.class;
            }

            @Override
            public String getColumnName(int columnIndex) {
                switch (columnIndex) {
                    case 0: return "File";
                    case 1: return "Offset / Extra";
                    case 2: return "Error";
                    default: throw new AssertionError();
                }
            }
        };
        initComponents();
        jErrorTable.getColumnModel().getColumn(1).setPreferredWidth(tfOffset.getPreferredSize().width);
        jErrorTable.getSelectionModel().addListSelectionListener(e -> {
            int row = jErrorTable.getSelectedRow();
            if (row < 0) {
                tfFileName.setText("");
                tfOffset.setText("");
                tfExtra.setText("");
                tfErrorMsg.setText("");
            } else {
                final FileError error = errors.get(row);
                final StringWriter stringWriter = new StringWriter();
                error.getError().printStackTrace(new PrintWriter(stringWriter));
                tfFileName.setText(error.getFile().toString());
                tfErrorMsg.setText(stringWriter.toString());
                tfErrorMsg.setCaretPosition(0);
                if (error instanceof FileOffsetError) {
                    tfOffset.setText(Long.toString(((FileOffsetError)error).getOffset()));
                    tfExtra.setText("");
                } else if (error instanceof FileErrorWithExtra) {
                    tfOffset.setText("");
                    tfExtra.setText(Objects.toString(((FileErrorWithExtra)error).getExtra()));
                } else {
                    tfOffset.setText("");
                    tfExtra.setText("");
                }
            }
        });
        if(!errors.isEmpty())
            jErrorTable.getSelectionModel().setSelectionInterval(0, 0);
    }

    public static MultipleErrorsDialog show(Component parent, String title, boolean modal, List<FileError> errors) {
        MultipleErrorsDialog dlg = new MultipleErrorsDialog(parent, title, modal, errors);
        dlg.setVisible(true);
        return dlg;
    }

    public static MultipleErrorsDialog show(Component parent, String title, boolean modal, FileError error) {
        return show(parent, title, modal, Collections.singletonList(error));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jErrorTable = new javax.swing.JTable();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        tfFileName = new javax.swing.JTextField();
        tfOffset = new javax.swing.JTextField();
        tfExtra = new javax.swing.JTextField();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        tfErrorMsg = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setName("Errors"); // NOI18N

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jErrorTable.setModel(errorTableModel);
        jErrorTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jErrorTable);

        jSplitPane1.setLeftComponent(jScrollPane1);

        tfFileName.setEditable(false);

        tfOffset.setEditable(false);
        tfOffset.setColumns(10);

        tfExtra.setEditable(false);

        tfErrorMsg.setColumns(20);
        tfErrorMsg.setRows(5);
        jScrollPane2.setViewportView(tfErrorMsg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tfFileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
            .addComponent(tfExtra)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );

        jSplitPane1.setBottomComponent(jPanel1);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTable jErrorTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tfErrorMsg;
    private javax.swing.JTextField tfExtra;
    private javax.swing.JTextField tfFileName;
    private javax.swing.JTextField tfOffset;
    // End of variables declaration//GEN-END:variables
}
