package mcworldinspector.utils;

import java.io.File;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author matthias
 */
public class MultipleErrorsDialog extends javax.swing.JDialog {

    private final AbstractTableModel errorTableModel;

    public MultipleErrorsDialog(java.awt.Frame parent, boolean modal, List<FileError> errors) {
        super(parent, modal);
        this.errorTableModel = new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return errors.size();
            }

            @Override
            public int getColumnCount() {
                return 3;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                final FileError error = errors.get(rowIndex);
                switch (columnIndex) {
                    case 0: return error.getFile().toString();
                    case 1:
                        if (error instanceof FileOffsetError)
                            return Long.toString(((FileOffsetError)error).getOffset());
                        else
                            return "";
                    case 2: return error.getError().toString();
                    default: throw new AssertionError();
                }
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return String.class;
            }

            @Override
            public String getColumnName(int columnIndex) {
                switch (columnIndex) {
                    case 0: return "File";
                    case 1: return "Offset";
                    case 2: return "Error";
                    default: throw new AssertionError();
                }
            }
            
        };
        initComponents();
        jErrorTable.getColumnModel().getColumn(1).setMaxWidth(jOffset.getPreferredSize().width);
        jErrorTable.getSelectionModel().addListSelectionListener(e -> {
            int row = jErrorTable.getSelectedRow();
            if (row < 0) {
                jFileName.setText("");
                jOffset.setText("");
                jErrorMsg.setText("");
            } else {
                final FileError error = errors.get(row);
                final StringWriter stringWriter = new StringWriter();
                error.getError().printStackTrace(new PrintWriter(stringWriter));
                jFileName.setText(error.getFile().toString());
                jErrorMsg.setText(stringWriter.toString());
                if (error instanceof FileOffsetError)
                    jOffset.setText(Long.toString(((FileOffsetError)error).getOffset()));
                else
                    jOffset.setText("");
            }
        });
        if(!errors.isEmpty())
            jErrorTable.getSelectionModel().setSelectionInterval(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jErrorTable = new javax.swing.JTable();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        jFileName = new javax.swing.JTextField();
        jOffset = new javax.swing.JTextField();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        jErrorMsg = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setName("Errors"); // NOI18N

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jErrorTable.setModel(errorTableModel);
        jErrorTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jErrorTable);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jFileName.setEditable(false);

        jOffset.setEditable(false);
        jOffset.setColumns(10);

        jErrorMsg.setColumns(20);
        jErrorMsg.setRows(5);
        jScrollPane2.setViewportView(jErrorMsg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jFileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );

        jSplitPane1.setBottomComponent(jPanel1);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea jErrorMsg;
    private javax.swing.JTable jErrorTable;
    private javax.swing.JTextField jFileName;
    private javax.swing.JTextField jOffset;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
