package mcworldinspector;

import javax.swing.event.ChangeListener;

/**
 *
 * @author matthias
 */
public class RenderOptionsPanel extends javax.swing.JPanel {

    public static enum Mode {
        SURFACE,
        SURFACE_NO_LEAVES,
        UNDERGROUND
    }

    public RenderOptionsPanel(Runnable cb) {
        initComponents();

        ChangeListener l = e -> cb.run();
        btnSurface.addChangeListener(l);
        btnSurfaceNoLeaves.addChangeListener(l);
        btnUnderground.addChangeListener(l);
        sliderLayer.addChangeListener(e -> {
            updateLabel();
            if(btnUnderground.isSelected())
                cb.run();
            else
                btnUnderground.setSelected(true);
        });
        cbPlayerMarker.addChangeListener(l);

        updateLabel();
    }

    public Mode getMode() {
        return btnSurface.isSelected() ? Mode.SURFACE :
                btnSurfaceNoLeaves.isSelected() ? Mode.SURFACE_NO_LEAVES :
                Mode.UNDERGROUND;
    }

    public int getLayer() {
        return sliderLayer.getValue();
    }

    public boolean getPlayerMarker() {
        return cbPlayerMarker.isSelected();
    }

    private void updateLabel() {
        btnUnderground.setText("Underground Y=" + getLayer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        renderModeGroup = new javax.swing.ButtonGroup();
        btnSurface = new javax.swing.JRadioButton();
        btnSurfaceNoLeaves = new javax.swing.JRadioButton();
        btnUnderground = new javax.swing.JRadioButton();
        sliderLayer = new javax.swing.JSlider();
        cbPlayerMarker = new javax.swing.JCheckBox();

        renderModeGroup.add(btnSurface);
        btnSurface.setSelected(true);
        btnSurface.setText("Surface");

        renderModeGroup.add(btnSurfaceNoLeaves);
        btnSurfaceNoLeaves.setText("Surface without leaves");

        renderModeGroup.add(btnUnderground);
        btnUnderground.setText("Underground");

        sliderLayer.setMaximum(255);
        sliderLayer.setMinimum(1);
        sliderLayer.setValue(64);

        cbPlayerMarker.setSelected(true);
        cbPlayerMarker.setText("Player Marker");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(sliderLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSurfaceNoLeaves)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSurface)
                                    .addComponent(btnUnderground))
                                .addGap(0, 281, Short.MAX_VALUE))
                            .addComponent(cbPlayerMarker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSurface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSurfaceNoLeaves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUnderground)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbPlayerMarker)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnSurface;
    private javax.swing.JRadioButton btnSurfaceNoLeaves;
    private javax.swing.JRadioButton btnUnderground;
    private javax.swing.JCheckBox cbPlayerMarker;
    private javax.swing.ButtonGroup renderModeGroup;
    private javax.swing.JSlider sliderLayer;
    // End of variables declaration//GEN-END:variables
}
